import { MenuItem, Translations, Testimonial } from '../types/index';

export const TRANSLATIONS: Translations = {
  en: {
    nav_home: "Home",
    nav_menu: "Menu",
    nav_about: "About",
    nav_contact: "Contact",
    hero_title: "Munira's Delights",
    hero_subtitle: "Baking Happiness for Every Occasion",
    hero_cta_order: "Order Now",
    hero_cta_explore: "Explore Menu",
    hero_est: "Est. 2024",
    typing_phrase_1: "Crafting Sweet Moments for Every Occasion",
    typing_phrase_2: "Where Every Bite Becomes a Celebration",
    typing_phrase_3: "Deliciously Made, Beautifully Delivered",
    typing_phrase_4: "Freshly Baked Happiness, Delivered to You",
    typing_phrase_5: "Your Celebrations, Our Culinary Art",
    typing_phrase_6: "Taste the Art of Munira’s Delights",
    typing_phrase_7: "We Bake. We Cook. We Deliver Joy.",
    menu_title: "Our Culinary Masterpieces",
    menu_subtitle: "Experience the perfect balance of flavor and artistry in every bite.",
    menu_selection: "Our Selection",
    menu_no_items: "No delicious items found in this category.",
    menu_filter_all: "All",
    menu_filter_cakes: "Cakes",
    menu_filter_pastries: "Pastries",
    menu_filter_catering: "Catering",
    menu_filter_icecream: "Ice Cream",
    order_step_1: "Select Delights",
    order_step_2: "Your Details",
    order_step_3: "Payment",
    order_step_4: "Proof",
    order_step_5: "Confirmation",
    btn_next: "Next Step",
    btn_back: "Back",
    btn_submit: "Finish Order",
    btn_upload: "Upload Screenshot",
    label_name: "Full Name",
    label_phone: "Phone Number",
    label_address: "Delivery Address",
    label_date: "Delivery Date",
    bank_instruction: "Please transfer the total amount to Account #100023456789 (Munira's Delights).",
    success_title: "Order Received!",
    success_message: "Thank you for choosing Munira's Delights. We are reviewing your order.",
    telegram_btn: "Send to Telegram",
    about_title: "Munira's Story",
    about_story: "\"Baking Happiness for Every Occasion\" is not just our tagline, it is our promise. Started from a small home kitchen, Munira's Delights has grown into a place where tradition meets elegance. Every cake, every pastry is crafted with love, using only the finest ingredients to make your celebrations unforgettable.",
    about_signature: "~ With Love, Munira",
    testimonials_title: "Client Love",
    contact_title: "Contact",
    contact_subtitle: "Get in Touch",
    contact_visit: "Visit Us",
    contact_call: "Call Us",
    contact_hours: "Opening Hours",
    footer_desc: "Sweetening your life, one bite at a time. Bringing joy to every celebration through the art of baking.",
    footer_rights: "All rights reserved.",
    footer_made_with: "Made with",
    footer_by: "by"
  },
  am: {
    nav_home: "መነሻ",
    nav_menu: "ምናሌ",
    nav_about: "ስለ እኛ",
    nav_contact: "ያግኙን",
    hero_title: "የሙኒራ ዴላይትስ",
    hero_subtitle: "ለእያንዳንዱ አጋጣሚ ደስታን መጋገር",
    hero_cta_order: "አሁን ይዘዙ",
    hero_cta_explore: "ምናሌን ያስሱ",
    hero_est: "የተመሰረተ 2016",
    typing_phrase_1: "ለእያንዳንዱ አጋጣሚ ጣፋጭ ጊዜያትን መፍጠር",
    typing_phrase_2: "እያንዳንዱ ጉርሻ በዓል የሚሆንበት",
    typing_phrase_3: "በጣፋጭነት የተሰራ፣ በሚያምር ሁኔታ የሚቀርብ",
    typing_phrase_4: "ትኩስ የተጋገረ ደስታ፣ ወደ እርስዎ የሚደርስ",
    typing_phrase_5: "የእርስዎ በዓላት፣ የእኛ የምግብ ጥበብ",
    typing_phrase_6: "የሙኒራ ዴላይትስን ጥበብ ይቅመሱ",
    typing_phrase_7: "እንጋግራለን። እናበስላለን። ደስታን እናደርሳለን።",
    menu_title: "የእኛ ጣፋጭ ምናሌ",
    menu_subtitle: "በእያንዳንዱ ጉርሻ ውስጥ የምርጥ ጣዕም እና የጥበብ ሚዛንን ይለማመዱ።",
    menu_selection: "የእኛ ምርጫዎች",
    menu_no_items: "በዚህ ምድብ ምንም ጣፋጭ ነገሮች አልተገኙም።",
    menu_filter_all: "ሁሉም",
    menu_filter_cakes: "ኬኮች",
    menu_filter_pastries: "ፓይስትሪ",
    menu_filter_catering: "ኬተሪንግ",
    menu_filter_icecream: "አይስ ክሬም",
    order_step_1: "እቃ ይምረጡ",
    order_step_2: "የእርስዎ መረጃ",
    order_step_3: "ክፍያ",
    order_step_4: "ማረጋገጫ ይስቀሉ",
    order_step_5: "ማረጋገጫ",
    btn_next: "ቀጣይ",
    btn_back: "ተመለስ",
    btn_submit: "ጨርስ",
    btn_upload: "ስክሪን ሾት ይምረጡ",
    label_name: "ሙሉ ስም",
    label_phone: "ስልክ ቁጥር",
    label_address: "የማድረሻ አድራሻ",
    label_date: "የማድረሻ ቀን",
    bank_instruction: "እባክዎ ጠቅላላውን ገንዘብ ወደ ሂሳብ ቁጥር #100023456789 ያስገቡ።",
    success_title: "ትዕዛዝዎ ተቀባይነት አግኝቷል!",
    success_message: "ስለታዘዙ እናመሰግናለን። ክፍያዎን እየገመገምን ነው።",
    telegram_btn: "ወደ ቴሌግራም ይላኩ",
    about_title: "የሙኒራ ታሪክ",
    about_story: "'ደስታን ለእያንዳንዱ አጋጣሚ መጋገር' መሪ ቃላችን ብቻ ሳይሆን ቃላችን ነው። ከትንሽ የቤት ውስጥ ኩሽና ተነስተን፣ ሙኒራ ዴላይትስ ወግ ከቅንጦት ጋር የሚገናኝበት ቦታ ሆኗል። እያንዳንዱ ኬክ፣ እያንዳንዱ ፓይስትሪ በፍቅር ተሠርቷል፣ ምርጥ ግብአቶችን በመጠቀም ክብረ በዓላችሁን የማይረሳ ለማድረግ።",
    about_signature: "~ በፍቅር፣ ሙኒራ",
    testimonials_title: "ደንበኞቻችን ምን ይላሉ",
    contact_title: "ያግኙን",
    contact_subtitle: "አብረን እንስራ",
    contact_visit: "ይጎብኙን",
    contact_call: "ይደውሉልን",
    contact_hours: "የስራ ሰዓት",
    footer_desc: "ሕይወትዎን እያጣፈጠ፣ በየጉርሻው። በመጋገር ጥበብ ለእያንዳንዱ በዓል ደስታን እናመጣለን።",
    footer_rights: "መብቱ በህግ የተጠበቀ ነው።",
    footer_made_with: "በ",
    footer_by: "የተሠራ በ"
  },
  ar: {
    nav_home: "الرئيسية",
    nav_menu: "القائمة",
    nav_about: "من نحن",
    nav_contact: "اتصل بنا",
    hero_title: "حلويات منيرة",
    hero_subtitle: "خبز السعادة لكل مناسبة",
    hero_cta_order: "اطلب الآن",
    hero_cta_explore: "استكشف القائمة",
    hero_est: "تأسست ٢٠٢٤",
    typing_phrase_1: "صياغة لحظات حلوة لكل مناسبة",
    typing_phrase_2: "حيث تصبح كل لقمة احتفالاً",
    typing_phrase_3: "صنع بلكذة، ويقدم بجمال",
    typing_phrase_4: "سعادة مخبوزة طازجة، تصل إليك",
    typing_phrase_5: "احتفالاتكم، فننا الطهوي",
    typing_phrase_6: "تذوق فن حلويات منيرة",
    typing_phrase_7: "نخبز. نطبخ. نوصل الفرح.",
    menu_title: "روائعنا الطهوية",
    menu_subtitle: "جرب التوازن المثالي بين النكهة والفن في كل لقشة.",
    menu_selection: "مختاراتنا",
    menu_no_items: "لا توجد أصناف لذيذة في هذه الفئة.",
    menu_filter_all: "الكل",
    menu_filter_cakes: "كيك",
    menu_filter_pastries: "معجنات",
    menu_filter_catering: "ضيافة",
    menu_filter_icecream: "آيس كريم",
    order_step_1: "اختر المنتجات",
    order_step_2: "بياناتك",
    order_step_3: "الدفع",
    order_step_4: "رفع الإثبات",
    order_step_5: "تأكيد",
    btn_next: "التالي",
    btn_back: "رجوع",
    btn_submit: "إنهاء الطلب",
    btn_upload: "اختر لقطة الشاشة",
    label_name: "الاسم الكامل",
    label_phone: "رقم الهاتف",
    label_address: "عنوان التوصيل",
    label_date: "تاريخ التوصيل",
    bank_instruction: "يرجى تحويل المبلغ الإجمالي إلى الحساب #100023456789.",
    success_title: "تم استلام الطلب!",
    success_message: "شكراً لاختياركم حلويات منيرة. نحن نراجع طلبك.",
    telegram_btn: "إرسال إلى تيليجرام",
    about_title: "قصة منيرة",
    about_story: "'خبز السعادة لكل مناسبة' ليس مجرد شعارنا، بل هو وعدنا. بدأت من مطبخ منزلي صغير، ونمت حلويات منيرة لتصبح مكاناً يلتقي فيه التقليد بالأناقة. كل كعكة، كل معجنات مصنوعة بحب، باستخدام أجود المكونات فقط لجعل احتفالاتكم لا تُنسى.",
    about_signature: "~ مع الحب، منيرة",
    testimonials_title: "آراء العملاء",
    contact_title: "اتصل بنا",
    contact_subtitle: "تواصل معنا",
    contact_visit: "زورونا",
    contact_call: "اتصل بنا",
    contact_hours: "ساعات العمل",
    footer_desc: "نحلي حياتك، لقمة تلو الأخرى. نجلب الفرح لكل احتفال من خلال فن الخبز.",
    footer_rights: "جميع الحقوق محفوظة.",
    footer_made_with: "صنع بـ",
    footer_by: "بواسطة"
  }
};

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: { en: 'Royal Rose Wedding Cake', am: 'ሮያል ሮዝ የሰርግ ኬክ', ar: 'كعكة الزفاف الملكية بالورد' },
    description: { en: 'Three-tier vanilla sponge with edible rose petals and gold leaf.', am: 'ባለ ሶስት ደረጃ የቫኒላ ኬክ ከሚበሉ ጽጌረዳዎች ጋር።', ar: 'كعكة إسفنجية من ثلاث طبقات مع بتلات الورد الصالحة للأكل وأوراق الذهب.' },
    price: 150,
    category: 'cakes',
    image: 'https://images.unsplash.com/photo-1535254973040-607b474cb50d?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: '2',
    name: { en: 'Luxury Cupcake Box', am: 'የቅንጦት ካፕ ኬክ ሳጥን', ar: 'صندوق كب كيك فاخر' },
    description: { en: 'Assorted gourmet cupcakes topped with artisan buttercream.', am: 'የተለያዩ ጣፋጭ ካፕ ኬኮች ከቅቤ ክሬም ጋር።', ar: 'تشكيلة كب كيك فاخرة مع كريمة الزبدة الحرفية.' },
    price: 25,
    category: 'cakes',
    image: 'https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: '3',
    name: { en: 'Artisan Croissants', am: 'ልዩ ክሮሳንቶች', ar: 'كرواسون حرفي' },
    description: { en: 'Golden, flaky, and buttery French pastries.', am: 'ወርቃማ እና ቅቤማ የፈረንሳይ ክሮሳንቶች።', ar: 'معجنات فرنسية ذهبية وهشة.' },
    price: 12,
    category: 'pastries',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f40388085?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: '4',
    name: { en: 'Grand Buffet Setup', am: 'ታላቅ የቡፌ ዝግጅት', ar: 'إعداد بوفيه كبير' },
    description: { en: 'Complete catering service with elegant food display.', am: 'ሙሉ የምግብ አቅርቦት አገልግሎት ከሚያምር አቀራረብ ጋር።', ar: 'خدمة ضيافة كاملة مع عرض طعام أنيق.' },
    price: 800,
    category: 'catering',
    image: 'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: '5',
    name: { en: 'Berry Bliss Ice Cream', am: 'የቤሪ አይስ ክሬም', ar: 'آيس كريم التوت' },
    description: { en: 'Hand-churned ice cream with fresh berry compote.', am: 'በእጅ የተሰራ አይስ ክሬም ከትኩስ ቤሪ ጋር።', ar: 'آيس كريم مصنوع يدوياً مع كومبوت التوت الطازج.' },
    price: 8,
    category: 'icecream',
    image: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: '6',
    name: { en: 'Dark Chocolate Gelato', am: 'የቸኮሌት ጄላቶ', ar: 'جيلاتو الشوكولاتة الداكنة' },
    description: { en: 'Intense dark chocolate churned to perfection.', am: 'ምርጥ የቸኮሌት ጣዕም ያለው አይስ ክሬም።', ar: 'شوكولاتة داكنة مكثفة مخفوقة بإتقان.' },
    price: 9,
    category: 'icecream',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80'
  }
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  { 
    id: 1, 
    name: { en: "Sarah J.", am: "ሳራ ጄ.", ar: "سارة ج." }, 
    text: { 
      en: "The wedding cake was absolutely stunning and tasted divine! Every guest was impressed by the details.", 
      am: "የሰርግ ኬኩ እጅግ በጣም ያምር ነበር እና ጣዕሙም ልዩ ነበር! እንግዶቹ ሁሉ በዝርዝሩ ተደንቀዋል።", 
      ar: "كانت كعكة الزفاف مذهلة للغاية وطعمها رائع! أعجب كل ضيف بالتفاصيل." 
    }, 
    rating: 5 
  },
  { 
    id: 2, 
    name: { en: "Ahmed K.", am: "አህመድ ኬ.", ar: "أحمد ك." }, 
    text: { 
      en: "Best pastries in town. The croissants remind me of the bakeries in Paris. Simply authentic.", 
      am: "በከተማ ውስጥ ምርጥ ፓይስትሪ። ክሮሳንቶቹ የፓሪስ ዳቦ ቤቶችን ያስታውሱኛል። በጣም ትክክለኛ።", 
      ar: "أفضل المعجنات في المدينة. الكرواسون يذكرني بمخابز باريس. أصيل ببساطة." 
    }, 
    rating: 5 
  },
  { 
    id: 3, 
    name: { en: "Bethelhem T.", am: "ቤተልሔም ቲ.", ar: "بيت لحم ت." }, 
    text: { 
      en: "Munira's catering made my daughter's birthday effortless and elegant. The presentation was art.", 
      am: "የሙኒራ ኬተሪንግ የልጄን ልደት ቀላል እና የሚያምር አደረገው። አቀራረቡ ጥበብ ነበር።", 
      ar: "جعلت ضيافة منيرة عيد ميلاد ابنتي سهلاً وأنيقاً. كان العرض فناً." 
    }, 
    rating: 4 
  },
];